name: delivery_boy
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  get: ^3.24.0
  flutter_screenutil: ^4.0.2+1
  flutter_svg: ^0.19.0
  webview_flutter:
  google_fonts: ^1.1.0
  pin_code_fields: ^6.0.2
  font_awesome_flutter: ^8.11.0
  rating_bar: ^0.2.0
  google_maps_flutter:  ^1.0.10
  geocoder: ^0.2.1 
  geocoding: ^1.0.5  
  geolocator: ^6.1.13
  flutter_launcher_icons: ^0.8.1
  carousel_pro: ^1.0.0
  fluttertoast: ^7.1.6
  image_picker: ^0.6.7+21
  image_cropper: ^1.3.1  
  shared_preferences: ^0.5.12+4
  progress_dialog: ^1.2.4
  cached_network_image: ^2.5.0
  flutter_slidable: ^0.5.7
  logger: ^0.9.4
  skeleton_text: ^2.0.2
  url_launcher: ^5.7.10
  flutter_local_notifications: 
  flutter_polyline_points: ^0.2.4
  cloud_firestore: ^0.14.3+1 
  firebase_core: ^0.5.2+1
  firebase_storage: ^4.0.0
  firebase_messaging: ^7.0.3
  flutter_cached_pdfview: 
  intl:
  location: ^2.3.5
  convex_bottom_bar: ^2.4.1
  firebase_database:





dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  assets:
    - assets/svgs/
    - assets/icons/
    

  
